### ISSUE TITLE
repo failed to connect to ml330

### ISSUE THREAD

**Issue by anthshor** [anthshor/oracle-grid#3]
[root@oracle65-4disk ~]# yum install oracle-rdbms-server-12cR1-preinstall
Loaded plugins: security
http://ml330.home.kikitux.net/stage/repo/OracleLinux/OL6/UEKR3/latest/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://ml330.home.kikitux.net/
stage/repo/OracleLinux/OL6/UEKR3/latest/x86_64/repodata/repomd.xml: (28, 'Operation too slow. Less than 1 bytes/sec transfered the last 30 seconds')
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: ol6_UEKR3_latest. Please verify its path and try again

Workaround in place - copy back original repo

**Comment by kikitux** [comment]
suggestion:
clean the /etc/yum.repos.d/*repo and use whatever repo you want to use.

**Comment by kikitux** [comment]
what commit did the trick?
